# Navigation Links
#   To link a homepage widget, specify the URL as a hash `#` followed by the filename of the
  #     desired widget in your `content/home/` folder.
  #   The weight parameter defines the order that the links will appear in.

main:
  # Bio
  - name: Bio
    url: /
    weight: 10

  # Publications & sub-menu
  - name: Publications
    identifier: works
    weight: 11

  - name: featured
    parent: works
    url: /#papers
    weight: 11

  - name: journals
    parent: works
    url: paper_journal/
    weight: 12

  - name: pre-prints
    parent: works
    url: paper_preprint/
    weight: 13

  # Conferences
  - name: Conferences
    identifier: confer
    weight: 15

  - name: selected
    parent: confer
    url: conference_selected/
    weight: 11

  - name: international
    parent: confer
    url: conference_international/
    weight: 12

  - name: domestic
    parent: confer
    url: conference_domestic/
    weight: 13


  # Patent
  - name: Patents
    url:  patent/
    weight: 20

  # News
  - name: News
    url: /#news
    weight: 30

  # Experience
  - name: Experiences
    url: experience/
    weight: 40

  ##############################################
  # - name: Bio
  #   url: /
  #   weight: 10

  # - name: Publications
  #   url: /#papers
  #   weight: 11

  # - name: TEST
  #   url: projects/
  #   weight: 12

  # - name: News
  #   url: /#news
  #   weight: 13

  # - name: Experiences
  #   url: experience/
  #   weight: 20